title: Meriam Maatallah 
logo: /1656768F-0FA1-48B9-8B60-67D9C71C7F55.jpeg
description: Second-year computer engineering student at ISIM Monastir with two years of experience in university projects. Passionate about technology, motivated, and eager to acquire new skills. Ready to
apply my commitment and enthusiasm within a professional team to make a significant contribution to innovative projects.
show_downloads: true 
theme: jekyll-theme-minimal
